### ISSUE TITLE
Documentation duplication

### ISSUE THREAD

**Issue by 2xB** [KATRIN-Experiment/Kassiopeia#73]
Currently there exist multiple public places of user documentation:
 * On the "gh-pages" branch
 * On the "main" branch in the `Kassiopeia/Documentation` folder
 * In the main README

As far as I can tell, the Doxygen-based documentation is worse than browsing the source at the moment, so we can also get rid of it and potentially do it again from scratch in the future. We should however keep the logos somewhere. So I suggest removing:
 * `Documentation/{Reference,CMakeLists.txt}`
 * `{KEMField,KGeoBag,Kommon}/Documentation/{Reference,CMakeLists.txt}`

I think we should move everything to the "main" branch in the "Documentation" folder since there people expect to find documentation and if people look for documentation for an old version of Kassiopeia, there they will look first.

Btw. there exists `KEMField/Documentation/manual/manual.pdf` which may make sense to link in the documentation as something like "KEMField Developer's Guide". Maybe it can also be compiled to Markdown using Pandoc to integrate it into the main documentation. But I think that's a challenge to solve after the above.

If this is agreed on, here are suggested tasks:
- [x] Forward https://katrin-experiment.github.io to https://katrin-experiment.github.io/Kassiopeia for now
- (Potentially Remove Doxygen-based documentation)
- [x]  Combine `gh-pages` and `main:Kassiopeia/Documentation/Reference`: #79 
- [x]  Bring resulting documentation to a reasonably named subdirectory of `main:Documentation`: #80 
- [x] Build GitHub Pages page via Action from `main:Documentation`: #80 
- [x] Remove `gh-pages` branch -- last commit: https://github.com/KATRIN-Experiment/Kassiopeia/commit/501d247a355d7d8ad1d7df84a40ab9df09240370
- [x] Reference or integrate `main:KEMField/Documentation/manual/manual.pdf` in the public documentation

**Comment by 2xB** [comment]
One could also add a citation file containing our paper as described in https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files .
